### ISSUE TITLE
Custom Enigma Exclusions

### ISSUE THREAD

**Issue by uGuardian** [uGuardian/RoR2Mods#1]
Add an Enigma exclusion setting that allows advanced users to set custom exclusions.

**Comment by Cerbiac** [comment]
Volcanic Egg would be a nice additional setting, particularly when you use Gesture of the Drowned.
Also, an option for disabling modded equipment with this enhancement would be nice, probably via comma-separated IDs.

**Comment by uGuardian** [comment]
Sorry for not noticing your comment sooner, it somehow escaped my notice.
I'll try to work on it in the next few days.
